In [16]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

#Importing S&P Data
SP_data = "..\Raw Data\S&P 500 Raw data_1-20-2017 ~ 3-21-2018.csv"
SP_df = pd.read_csv(SP_data, encoding = "ISO-8859-1")
SP_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2017-01-20,2269.959961,2276.959961,2265.010010,2271.310059,2271.310059,3524970000
1,2017-01-23,2267.780029,2271.780029,2257.020020,2265.199951,2265.199951,3152710000
2,2017-01-24,2267.879883,2284.629883,2266.679932,2280.070068,2280.070068,3810960000
3,2017-01-25,2288.879883,2299.550049,2288.879883,2298.370117,2298.370117,3846020000
4,2017-01-26,2298.629883,2300.989990,2294.080078,2296.679932,2296.679932,3610360000